### ISSUE TITLE
Icons not aligned to grid and thus blurry

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#908]
The gate is definitely messed up:
https://github.com/Templarian/MaterialDesign/issues/807#issuecomment-154948501

The 3rd circle in format-list-bulleted ~~has a different size and looks weird, and it's actually like that in the original Google icon~~ (should be fixed nonetheless IMO):
[![format-list-bulleted](https://materialdesignicons.com/icon/format-list-bulleted)](https://materialdesignicons.com/icon/format-list-bulleted)

I believe I've seen a few more broken ones, will add them to this issue as I stumble upon them.

**Comment by CoDEmanX** [comment]
`sim` is everything but pixel perfect:
[![sim](https://materialdesignicons.com/icon/sim)](https://materialdesignicons.com/icon/sim)

**Comment by Templarian** [comment]
Both are fixed (images above will update once the cache expires on github).

**Comment by CoDEmanX** [comment]
Thanks. `gate` is still broken though:

[![gate](https://materialdesignicons.com/icon/gate)](https://materialdesignicons.com/icon/gate)

**Comment by CoDEmanX** [comment]
The pause icon is apparently broken as well:

[![pause](https://materialdesignicons.com/icon/pause)](https://materialdesignicons.com/icon/pause)

**Comment by Templarian** [comment]
- [x] pause
- [x] pause-circle
- [x] pause-circle-outline
- [x] play-circle
- [x] play-circle-outline
- [x] skip-next
- [x] skip-previous

I checked a lot of the media icons to verify these were the only ones.
